# -*- coding: utf-8 -*-
"""1.BuscaEmLarguraBFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NeuI2-l6aCob2w-TjfPesNZVASqkm9v

# Algoritmo: Busca em Largura (BFS)
"""

import time
from collections import deque

GOAL_STATE = (1, 2, 3, 4, 5, 6, 7, 8, 0)

class Node:
    def __init__(self, state, parent=None, action=None):
        self.state = state
        self.parent = parent
        self.action = action

def get_successors(node):
    successors = []
    state = node.state
    empty_idx = state.index(0)
    row, col = divmod(empty_idx, 3)
    moves = [(-1, 0, 'CIMA'), (1, 0, 'BAIXO'), (0, -1, 'ESQUERDA'), (0, 1, 'DIREITA')]
    for dr, dc, action in moves:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_empty_idx = new_row * 3 + new_col
            new_state = list(state)
            new_state[empty_idx], new_state[new_empty_idx] = new_state[new_empty_idx], new_state[empty_idx]
            child_node = Node(tuple(new_state), node, action)
            successors.append(child_node)
    return successors

def get_path(node):
    path = []
    while node.parent is not None:
        path.append(node.action)
        node = node.parent
    path.reverse()
    return path

def bfs(initial_state):
    start_time = time.time()
    start_node = Node(initial_state)
    if start_node.state == GOAL_STATE:
        return start_node, 0, time.time() - start_time
    frontier = deque([start_node])
    explored = {initial_state}
    nodes_expanded = 0

    while frontier:
        current_node = frontier.popleft()
        nodes_expanded += 1
        for child in get_successors(current_node):
            if child.state not in explored:
                if child.state == GOAL_STATE:
                    return child, nodes_expanded, time.time() - start_time
                explored.add(child.state)
                frontier.append(child)
    return None, nodes_expanded, time.time() - start_time



# EXECUÇÃO
print("Executando BFS...\n")
tabuleiro = (8,0,6,5,4,7,2,3,1)
no_vencedor, total_testado, tempo = bfs(tabuleiro)

if no_vencedor:
    solucao = get_path(no_vencedor)
    print("Solução encontrada!")
    print(f"Movimentos: {len(solucao)}")
    print(f"Nós explorados: {total_testado}")
    print(f"Tempo: {tempo:.4f} segundos")
    print(f"Caminho: {solucao}")