# -*- coding: utf-8 -*-
"""2.1Busca em ProfundidadeDFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LiLzORo1o0KPMSp9UpvV7PrJLhddYEPL

# Algoritmo: Busca em Profundidade (DFS)
"""

import time
GOAL_STATE = (1, 2, 3, 4, 5, 6, 7, 8, 0)

class Node:
    def __init__(self, state, parent=None, action=None):
        self.state = state
        self.parent = parent
        self.action = action

def get_path(node):
    path = []
    while node.parent is not None:
        path.append(node.action)
        node = node.parent
    path.reverse()
    return path

def get_successors(node):
    successors = []
    state = node.state
    empty_idx = state.index(0)
    row, col = divmod(empty_idx, 3)

    moves = [(-1, 0, 'CIMA'), (1, 0, 'BAIXO'), (0, -1, 'ESQUERDA'), (0, 1, 'DIREITA')]

    for dr, dc, action in moves:
        new_row, new_col = row + dr, col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_empty_idx = new_row * 3 + new_col

            new_state = list(state)
            new_state[empty_idx], new_state[new_empty_idx] = new_state[new_empty_idx], new_state[empty_idx]

            child_node = Node(tuple(new_state), node, action)
            successors.append(child_node)

    return successors

def dfs(initial_state, max_nodes=100000):
    start_time = time.time()
    start_node = Node(initial_state)

    # Pilha (LIFO) guarda objetos Node
    stack = [start_node]
    visited = set()
    nodes_expanded = 0

    while stack:
        # Tira o último NÓ adicionado
        current_node = stack.pop()
        nodes_expanded += 1

        # Proteção contra travamento
        if nodes_expanded > max_nodes:
            print("Limite de nós atingido! Interrompendo execução.")
            return None, nodes_expanded, time.time() - start_time

        # Verifica objetivo comparando o estado do nó
        if current_node.state == GOAL_STATE:
            return get_path(current_node), nodes_expanded, time.time() - start_time

        # Marca como visitado e expande
        if current_node.state not in visited:
            visited.add(current_node.state)

            # Expande vizinhos
            for child in get_successors(current_node):
                stack.append(child)

    return None, nodes_expanded, time.time() - start_time

#  EXECUÇÃO
tabuleiro = (8,0,6,5,4,7,2,3,1)

print("Iniciando Busca em Profundidade (DFS)...\n")

solucao, nos, tempo = dfs(tabuleiro)


if solucao:
    print("Solução encontrada!")
    print(f"Movimentos: {len(solucao)}")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")
    print(f"Caminho: {solucao}")
else:
    print("Não encontrou solução.")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")