# -*- coding: utf-8 -*-
"""2.2BuscaEmProfundidadeLimitadaDLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWOZuov40o5IaPMPLyCeOqBkH6dPqcCc

# Algoritmo: Busca em Profundidade Limitada (DLS)
"""

import time
GOAL_STATE = (1, 2, 3, 4, 5, 6, 7, 8, 0)
class Node:
    def __init__(self, state, parent=None, action=None, depth=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.depth = depth

def get_path(node):
    path = []
    while node.parent is not None:
        path.append(node.action)
        node = node.parent
    path.reverse()
    return path

def get_successors(node):
    successors = []
    state = node.state
    empty_idx = state.index(0)
    row, col = divmod(empty_idx, 3)

    moves = [(-1, 0, 'CIMA'), (1, 0, 'BAIXO'), (0, -1, 'ESQUERDA'), (0, 1, 'DIREITA')]

    for dr, dc, action in moves:
        nr, nc = row + dr, col + dc

        if 0 <= nr < 3 and 0 <= nc < 3:
            new_idx = nr * 3 + nc

            new_state = list(state)
            new_state[empty_idx], new_state[new_idx] = new_state[new_idx], new_state[empty_idx]

            child_node = Node(tuple(new_state), parent=node, action=action, depth=node.depth + 1)
            successors.append(child_node)

    return successors

def dls(initial_state, limit):
    start_time = time.time()
    start_node = Node(initial_state, depth=0)

    stack = [start_node]

    # Conjunto para estados visitados
    visited = set()
    nodes_expanded = 0

    while stack:
        current_node = stack.pop()
        nodes_expanded += 1

        # Verifica se o estado atual é o objetivo
        if current_node.state == GOAL_STATE:
            # Reconstrói o caminho final apenas no momento de sucesso
            return get_path(current_node), nodes_expanded, time.time() - start_time

        # Verifica se ainda não atingiu o limite de profundidade estipulado
        if current_node.depth < limit:
            if current_node.state not in visited:
                visited.add(current_node.state)

                # Expande os vizinhos (que já retornam formatados como Nodes)
                for child in get_successors(current_node):
                    stack.append(child)

    # Retorna None caso a pilha esvazie sem encontrar o objetivo dentro do limite
    return None, nodes_expanded, time.time() - start_time


# EXECUÇÃO
tabuleiro = (8,0,6,5,4,7,2,3,1)

print("Executando DLS...\n")

# Pode ajustar o limite como desejar
solucao, nos, tempo = dls(tabuleiro, limit=20
                          )

# RESULTADOS

if solucao:
    print("Solução encontrada!")
    print(f"Movimentos: {len(solucao)}")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")
    print(f"Caminho: {solucao}")
else:
    print("Não encontrou solução.")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")