# -*- coding: utf-8 -*-
"""2.3BuscaEmAprofundamentoIterativoIDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193VBbuiN9-4VA6wmQM2rNU0WaqWVTIeF

# Algoritmo: Busca em Aprofundamento Iterativo (IDS)
"""

import time

GOAL_STATE = (1, 2, 3, 4, 5, 6, 7, 8, 0)

class Node:
    def __init__(self, state, parent=None, action=None, depth=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.depth = depth

def get_path(node):
    path = []
    while node.parent is not None:
        path.append(node.action)
        node = node.parent
    path.reverse()
    return path

def get_successors(node):
    successors = []
    state = node.state
    empty_idx = state.index(0)
    row, col = divmod(empty_idx, 3)

    moves = [(-1, 0, 'CIMA'), (1, 0, 'BAIXO'), (0, -1, 'ESQUERDA'), (0, 1, 'DIREITA')]

    for dr, dc, action in moves:
        nr, nc = row + dr, col + dc
        if 0 <= nr < 3 and 0 <= nc < 3:
            new_idx = nr * 3 + nc
            new_state = list(state)
            new_state[empty_idx], new_state[new_idx] = new_state[new_idx], new_state[empty_idx]

            # Cria o filho herdando o pai, registando a ação e somando 1 na profundidade
            child_node = Node(tuple(new_state), parent=node, action=action, depth=node.depth + 1)
            successors.append(child_node)

    return successors

def dls(initial_state, limit):
    # O nó raiz inicia com profundidade 0
    start_node = Node(initial_state, depth=0)

    stack = [start_node]
    visited = set()
    nodes_expanded = 0

    while stack:
        current_node = stack.pop()
        nodes_expanded += 1

        # Verifica se chegou no objetivo
        if current_node.state == GOAL_STATE:
            return get_path(current_node), nodes_expanded

        # Expande apenas se não atingiu o limite daquela iteração
        if current_node.depth < limit:
            if current_node.state not in visited:
                visited.add(current_node.state)

                for child in get_successors(current_node):
                    stack.append(child)

    return None, nodes_expanded

def ids(initial_state, max_depth=40):
    start_time = time.time()
    total_nodes_expanded = 0

    # Vai rodar a DLS aumentando o limite de 0 até max_depth
    for depth in range(max_depth):
        result, nodes_in_this_depth = dls(initial_state, limit=depth)
        total_nodes_expanded += nodes_in_this_depth

        # Se encontrou a solução (result não é None), encerra o algoritmo
        if result is not None:
            return result, total_nodes_expanded, time.time() - start_time

    return None, total_nodes_expanded, time.time() - start_time


# EXECUÇÃO
tabuleiro = (8,0,6,5,4,7,2,3,1)

solucao, nos, tempo = ids(tabuleiro)

if solucao:
    print("Solução  encontrada!")
    print(f"Movimentos: {len(solucao)}")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")
    print(f"Caminho: {solucao}")
else:
    print("Não encontrou solução.")
    print(f"Nós explorados: {nos}")
    print(f"Tempo: {tempo:.6f} segundos")