# -*- coding: utf-8 -*-
"""3.1AlgoritmoAStar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-ZAL-E2wjkrW3qGL6oXRFLBPd5JgDy8

# Algoritmo: A* (Busca Informada)
"""

import time
import heapq

GOAL_STATE = (1,2,3,4,5,6,7,8,0)

class Node:
    def __init__(self, state, parent=None, action=None, g=0, h=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.g = g  # Custo do caminho do início até aqui
        self.h = h  # Estimativa heurística até o objetivo
        self.f = g + h  # Custo total estimado

    # Necessário para a fila de prioridade comparar nós com o mesmo valor de f
    def __lt__(self, other):
        return self.f < other.f

def get_path(node):
    path = []
    while node.parent is not None:
        path.append(node.action)
        node = node.parent
    path.reverse()
    return path

def get_successors(node, heuristic):
    successors = []
    state = node.state
    empty_idx = state.index(0)
    row, col = divmod(empty_idx, 3)

    moves = [(-1, 0, 'CIMA'), (1, 0, 'BAIXO'), (0, -1, 'ESQUERDA'), (0, 1, 'DIREITA')]

    for dr, dc, action in moves:
        nr, nc = row + dr, col + dc
        if 0 <= nr < 3 and 0 <= nc < 3:
            new_idx = nr * 3 + nc
            new_state = list(state)
            new_state[empty_idx], new_state[new_idx] = new_state[new_idx], new_state[empty_idx]

            # g = custo do pai + 1
            # h = calculado pela função heurística passada
            new_state_tuple = tuple(new_state)
            child_node = Node(
                state=new_state_tuple,
                parent=node,
                action=action,
                g=node.g + 1,
                h=heuristic(new_state_tuple)
            )
            successors.append(child_node)
    return successors

# Heurística 1: Peças fora do lugar

def h_misplaced(state):
    return sum(1 for i in range(9) if state[i] != 0 and state[i] != GOAL_STATE[i])


# Heurística 2: Distância de Manhattan

def h_manhattan(state):
    distance = 0
    for i in range(9):
        if state[i] != 0:
            goal_pos = GOAL_STATE.index(state[i])
            x1, y1 = divmod(i, 3)
            x2, y2 = divmod(goal_pos, 3)
            distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

def astar(initial_state, heuristic):
    start_time = time.time()

    # O nó inicial tem custo g=0 e h calculado
    start_node = Node(initial_state, g=0, h=heuristic(initial_state))

    # A open_list guarda os objetos Node. O heapq usará o f (devido ao __lt__)
    open_list = []
    heapq.heappush(open_list, start_node)

    visited = {} # Guardamos o estado: menor custo g encontrado
    nodes_expanded = 0

    while open_list:
        current_node = heapq.heappop(open_list)
        nodes_expanded += 1

        if current_node.state == GOAL_STATE:
            return get_path(current_node), nodes_expanded, time.time() - start_time

        # Se já visitamos este estado com um custo menor ou igual, pulamos
        if current_node.state in visited and visited[current_node.state] <= current_node.g:
            continue

        visited[current_node.state] = current_node.g

        for child in get_successors(current_node, heuristic):
            heapq.heappush(open_list, child)

    return None, nodes_expanded, time.time() - start_time

# Execução

tabuleiro = (8,0,6,5,4,7,2,3,1)

print("A* com Heurística 1 (Peças fora do lugar):")
sol1, nos1, tempo1 = astar(tabuleiro, h_misplaced)

print(f"Movimentos: {len(sol1)}")
print(f"Nós: {nos1}")
print(f"Tempo: {tempo1:.6f}\n")
print(f"Caminho: {sol1}")


print("A* com Heurística 2 (Manhattan):")
sol2, nos2, tempo2 = astar(tabuleiro, h_manhattan)

print(f"Movimentos: {len(sol2)}")
print(f"Nós explorados: {nos2}")
print(f"Tempo: {tempo2:.6f}")
print(f"Caminho: {sol2}")